version: 2
updates:
  # Keep bundler dependencies up to date
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "dlrobson"
    # Create a group of dependencies to be updated together in one pull request
    # The PR name will be dev-dependencies
    groups:
      dev-dependencies:
        # All dependencies will be updated together in a single PR
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "dlrobson"
    # Create a group of dependencies to be updated together in one pull request
    # The PR name will be dev-dependencies
    groups:
      dev-dependencies:
        # All dependencies will be updated together in a single PR
        patterns:
          - "*"
