name: Cleanup Pull Request Images

# We create an image for each PR that modifies files that impact the final build image.
# This action deletes the image created for the PR when the PR is closed. If a PR is
# reopened, the image will end up being rebuilt.

on:
  pull_request:
    types: [closed]

env:
  PACKAGE_NAME: ${{ github.event.repository.name }}-build-env

jobs:
  ghcr-cleanup-image:
    name: ghcr cleanup action
    runs-on: ubuntu-latest
    steps:
      - name: Delete image
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: ${{ env.PACKAGE_NAME }}
          tags: PR-${{github.event.pull_request.number}}
          token: ${{ secrets.GITHUB_TOKEN }}
