# TODO(dan): This can build the Build Image and push to github packages. The build workflow can depend on this workflow.
name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
