name: Code Quality Checks

# Only run on push to branches other than main. We'll assume that the checks
# needed to pass before merging to main are run on main itself.
on: [pull_request]

env:
  CARGO_TERM_COLOR: always

# This stops any running jobs when a new commit is pushed
# Reference: https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  quality-check:
    runs-on: ubuntu-latest
    container:
      image: rust:slim
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Check Rust formatting
        if: ${{ !cancelled() }}
        run: cargo fmt --check

      - name: Install curl
        if: ${{ !cancelled() }}
        run: apt-get update && apt-get install -y curl

      - uses: cargo-bins/cargo-binstall@main

      - name: Install cargo-spellcheck
        if: ${{ !cancelled() }}
        run: cargo binstall --no-symlinks -y cargo-spellcheck

      - name: Check spelling
        if: ${{ !cancelled() }}
        run: cargo-spellcheck check

      # Add Clippy here